"""Define shared constants for the RAG pipeline."""

SPAN_DIVERSITY = "diversity_selection"
SPAN_FUSION = "fusion"
SPAN_GENERATION = "generation"
SPAN_KEYWORD_SEARCH = "keyword_search"
SPAN_RERANKING = "reranking"
SPAN_RETRIEVAL = "retrieval_pipeline"
SPAN_STREAM = "stream_response"
SPAN_VECTOR_SEARCH = "vector_search"
